### ISSUE TITLE
visual studio code error

### ISSUE THREAD

**Issue by opemy** [castrojo/awesome-immutable#22]

**Comment by opemy** [comment]
'''
"solidity"

const ethers = require("ethers");
const fs = require("fs-extra");

async function main() {
    // compile them in our code
    // compile them seperately
    // http://0.0.0.0:8545
    const provider = new ethers.providers.JsonRpcProvider("http://127.0.0.1:7545");
    const wallet = new ethers.wallet(
        "06d882fb5427601d7640a66351f1532b6568cc8f3489cc19146cb6eca3e89917",
        provider
    );
    const abi = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.abi", "utf8");
    const binary = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.bin",
        "utf8"
    );
    const contractFactory = new ethers.contractFactory(abi, binary, wallet);
    console.log("Deploying, please wait...");
    const contract = await contractFactory.deploy();
    console.log(contract);
}
main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
,,,,
please i'm running error on this code
PS C:\Users\user\Downloads\ubuntu-20.04-desktop-amd64> node deploy.js
TypeError: ethers.wallet is not a constructor
    at main (C:\Users\user\Downloads\ubuntu-20.04-desktop-amd64\deploy.js:9:20)
    at Object.<anonymous> (C:\Users\user\Downloads\ubuntu-20.04-desktop-amd64\deploy.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
,,,,,,
can someone help me?
